# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6ba462230df21e18db855b3e9c49291f05316f6b3d105d6751fed24f650872eea300012caa65f25cdc4f2da22a1b9bb20776ee7034d97c9fe255fabf4cc70ff

test:
  secret_key_base: a7a342926a157e53fb9a8f44821eeaa6f1b3d1845d5ab3fe8451e1e1ddf30fb40f94ec4db069db252b5adb02cbb41169595a7c0670a8dbbb7fda6e87ad42631e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
